name = "cloudflare-mtls-manager"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "mtls-db"
database_id = "9c0878c8-eba5-4e8b-97b2-156824cb9cef"
