name = "cloudflare-mtls-cron"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[triggers]
crons = ["0 8 * * *"] # Run daily at 8:00 AM

[[d1_databases]]
binding = "DB"
database_name = "mtls-db-preview"
database_id = "a301fbf7-e335-472e-a7a1-83dd11d9950c"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "mtls-db"
database_id = "9c0878c8-eba5-4e8b-97b2-156824cb9cef"
